export enum DashboardConstants {
    status = 'status',
    issueNumber = 'issueNumber',
    title = 'title',
    createdDate = 'createdDate',
    reporter = 'reporter',
    assignee = 'assignee',
    view = 'view',
    allIssues = 'All-issues',
    myIssues = 'My-issues',
    inBacklog = 'In-backlog',
    inProgress = 'In-progress',
    inTest = 'In-test',
    done = 'Done',
    issueTemplate = 'issueTemplate',
    notificationTemplate = 'notificationTemplate',
    data = 'data',
    assigneeName = 'assigneeName',
    IssueReport = 'IssueReport',
    modalLg = 'modal-lg',
    modalMd = 'modal-md'
}
