export enum IssueFormConstants {
    reporterName = 'reporterName',
    reporterUserId = 'reporterUserId',
    attachments = 'attachments',
    assigneeName = 'assigneeName',
    file = 'file',
    filename = 'filename',
    originalFileName = 'originalFileName',
    bug = 'Bug',
    newFeature = 'New Feature',
    improvement = 'Improvement',
    task = 'Task',
    inBacklog = 'In-backlog',
    inProgress = 'In-progress',
    inReview = 'In-review',
    inTest = 'In-test',
    done = 'Done',
    highest = 'Highest',
    high = 'High',
    medium = 'Medium',
    low = 'Low',
    lowest = 'Lowest',
    title = 'title',
    lastUpdatedDate = 'lastUpdatedDate',
    lastUpdatedBy = 'lastUpdatedBy'
}
